# 넘파이 (Numpy)
- ndim : 축의개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총개수
- dtype : 배열 원소의 자료형

### 1차원과 속성들

In [12]:
list = [11,22,33,44,55]
import numpy as np
narr = np.array(range(7))
print(narr)
print(type(narr))
print(narr.ndim)
print(narr.shape)
print(narr.size)
print(narr.dtype)
print(narr[3])
print(narr[2:5])

[0 1 2 3 4 5 6]
<class 'numpy.ndarray'>
1
(7,)
7
int64
3
[2 3 4]


In [15]:
narr1 = np.array([1,2,3,4]) # int64
narr2 = np.array([1,2,'apple','banana'])
narr3 = np.array([1,2,3,4], dtype='str')
print(narr1, narr1.dtype)
print(narr2, narr2.dtype)
print(narr3, narr3.dtype)

[1 2 3 4] int64
['1' '2' 'apple' 'banana'] <U21
['1' '2' '3' '4'] <U1


In [28]:
narr4 = np.zeros(10, dtype='int64')
narr5 = np.ones(10, dtype='int64')
narr6 = np.full(5,2, dtype='float64')
narr7 = np.full(5,'ok')
narr8 = np.linspace(0,10,5, endpoint=False)
narr9 = np.arange(10)
print(narr4, narr4.dtype)
print(narr5, narr5.dtype) 
print(narr6, narr6.dtype) 
print(narr7, narr7.dtype) 
print(narr8, narr8.dtype) 
print(narr9, narr9.dtype) 

[0 0 0 0 0 0 0 0 0 0] int64
[1 1 1 1 1 1 1 1 1 1] int64
[2. 2. 2. 2. 2.] float64
['ok' 'ok' 'ok' 'ok' 'ok'] <U2
[0. 2. 4. 6. 8.] float64
[0 1 2 3 4 5 6 7 8 9] int64


In [45]:
# 2차원
arr1 = np.zeros((2,2))
arr2 = np.ones((2,2))
arr3 = np.full((2,2),5)
arr4 = np.eye(2)   ## 단위행렬
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)
print(arr3,arr3.dtype)
print(arr4,arr4.dtype)

[[0. 0.]
 [0. 0.]] float64
[[1. 1.]
 [1. 1.]] float64
[[5 5]
 [5 5]] int64
[[1. 0.]
 [0. 1.]] float64


In [49]:
# 2차원 배열
nar = np.array([[1,2],[3,4]])
print(nar, nar.ndim, nar.dtype, nar.shape, nar.size, type(nar))

[[1 2]
 [3 4]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [57]:
# 2차원 타입변환
nar1 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
nar2 = np.arange(1,10).reshape(3,3)
nar3 = np.arange(1,11).reshape(2,5)
nar4 = np.arange(1,11).reshape(5,2)
nar5 = np.arange(1,28).reshape(3,3,3)
print(nar1, nar1.ndim, nar1.dtype, nar1.shape, nar1.size, type(nar1))
print(nar2, nar2.ndim, nar2.dtype, nar2.shape, nar2.size, type(nar2))
print(nar3, nar3.ndim, nar3.dtype, nar3.shape, nar3.size, type(nar3))
print(nar4, nar4.ndim, nar4.dtype, nar4.shape, nar4.size, type(nar4))
print(nar5, nar5.ndim, nar5.dtype, nar5.shape, nar5.size, type(nar5))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 2 int64 (2, 5) 10 <class 'numpy.ndarray'>
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 2 int64 (5, 2) 10 <class 'numpy.ndarray'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 3 int64 (3, 3, 3) 27 <class 'numpy.ndarray'>


In [78]:
# 2차원 타입변환(응용)
nar1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]).reshape(3,7)
nar2 = np.array([1,2,3,4,5,6,7]).reshape(7,1)
nar3 = np.array([1,2,3,4,5,6,7,8,9,10]).reshape(5,2)
nar4 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]).reshape(3,7)
print(nar1, nar1.ndim, nar1.dtype, nar1.shape, nar1.size, type(nar1))
print("================================")
print(nar2, nar2.ndim, nar2.dtype, nar2.shape,nar2.size, type(nar2))
print("================================")
print(nar3, nar3.ndim, nar3.dtype, nar3.shape,nar3.size, type(nar3))
print("================================")
print(nar4, nar4.ndim, nar4.dtype, nar4.shape,nar4.size, type(nar4))
print("================================")

# 3차원 타입변환(응용)
nar5 = np.array([1,2,3,4,5,6,7,8,9,10,11,12]).reshape(4,3,1)
print(nar5, nar5.ndim, nar5.dtype, nar5.shape, nar5.size, type(nar5))

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 2 int64 (3, 7) 21 <class 'numpy.ndarray'>
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] 2 int64 (7, 1) 7 <class 'numpy.ndarray'>
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 2 int64 (5, 2) 10 <class 'numpy.ndarray'>
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 2 int64 (3, 7) 21 <class 'numpy.ndarray'>
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]] 3 int64 (4, 3, 1) 12 <class 'numpy.ndarray'>


In [82]:
t1 = np.arange(1,22).reshape(3,7)
t2 = np.arange(1,8).reshape(7,1)
t3 = np.arange(1,11).reshape(5,2)
t4 = np.arange(1,13).reshape(4,3,1)
print(t1)
print("="*23)
print(t2)
print("="*23)
print(t3)
print("="*23)
print(t4)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [103]:
print(t1[1][2:5])
print(t1[1:3, 2:5])
# 브로드캐스팅
print(t1 * 10)
print(t1 % 2 == 0)
print(t1[t1 % 2 == 0])

[10 11 12]
[[10 11 12]
 [17 18 19]]
[[ 10  20  30  40  50  60  70]
 [ 80  90 100 110 120 130 140]
 [150 160 170 180 190 200 210]]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]


In [102]:
l1= [6,7,8,9,10]
l2 = [1,2,3,4,5]
print(l1 + l2)
np1 = np.array(l1)
np2 = np.array(l2)
np3 = np1 + np2
print(np3.tolist())
print("덧셈:",np1 + np2)
print("뺄셈:",np1 - np2)
print("곱셈:",np1 * np2)
print("나눗셈:",np1 / np2)

[6, 7, 8, 9, 10, 1, 2, 3, 4, 5]
[7, 9, 11, 13, 15]
덧셈: [ 7  9 11 13 15]
뺄셈: [5 5 5 5 5]
곱셈: [ 6 14 24 36 50]
나눗셈: [6.         3.5        2.66666667 2.25       2.        ]


In [106]:
# flatten 처리
ff = np.arange(1,10).reshape(3,3)
print(ff)
print(ff.reshape(9))
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


### Random number 발생
- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.normal(): 정규 분포 난수 생성

In [107]:
# randomint
# RGB (세로픽셀수, 가로픽셀, 색상채널)
x = np.random.randint(0,255,size=(3,3,3))
x 

array([[[ 50,  56,  34],
        [  0,  28,  51],
        [ 74, 228,  53]],

       [[182,  84,  33],
        [ 20, 124, 205],
        [ 77, 244,  65]],

       [[ 52,   3, 175],
        [229, 159, 148],
        [110,  19,  89]]])

In [112]:
print('평균값:',np.mean(x),'표준편차:',np.std(x),'최소값:',x.min(),'최대값:',x.max())

평균값: 96.0 표준편차: 72.95863871374631 최소값: 0 최대값: 244


In [115]:
x2 = np.random.normal(5,3,(10,5)) # 평균이 5, 표준편차가 3
x2

array([[ 7.56000949,  6.42029808,  8.25689878,  1.4571143 ,  6.70878227],
       [ 3.28316792,  6.54396418,  4.98457853,  5.40936389,  6.08744866],
       [10.45406282,  6.1771995 ,  5.41363044,  1.52885719,  2.50001108],
       [ 6.40712859,  7.71370473,  9.82030557,  9.21985008,  5.39563186],
       [ 5.9695838 ,  0.74926081,  7.84559521,  6.42278922,  3.65349839],
       [ 5.51289306,  5.09191341,  6.4105953 ,  4.51468358,  3.6149891 ],
       [ 6.45476367,  2.94407171,  1.14298448,  2.75419433,  4.33060104],
       [ 6.38931282,  3.93827367,  0.83246131,  0.31999718,  3.85777539],
       [ 7.17061004,  5.71566953,  5.08851843,  1.80376219,  7.38233186],
       [ 3.39987362,  6.03095794,  3.82176399,  9.39374648,  5.19281615]])

In [116]:
x3 = np.random.randn(10,5) # 표준 정규 분포 난수 생성
x3

array([[ 1.56280578, -0.35154093,  0.01945387,  0.54969489,  0.48853919],
       [-0.09085504, -1.33322806,  0.34397893,  0.09086659, -0.28687476],
       [-0.79234509,  0.67321804, -1.5111526 ,  0.75043914,  0.41268444],
       [-1.92754429,  0.31152486, -0.13550666,  0.37719818, -0.71200474],
       [ 0.74189698,  0.29324231,  1.06762253, -0.0720019 ,  0.28705627],
       [-0.22340396,  0.36878411, -0.45314064, -0.7263755 ,  0.47287185],
       [-0.29972476,  1.0678279 ,  0.02454032,  0.46427791, -1.53157249],
       [-0.04390312,  1.99248437, -0.62161985, -1.33022006,  0.64130958],
       [ 0.49156131,  0.84070462, -0.75748364, -1.32834044, -0.51222514],
       [-0.3266795 , -1.03143772,  0.7923366 ,  0.6404544 ,  0.74079435]])

In [120]:
x4 = np.array([3,1,2,3,5,0,4,5,0,5,0,44,5,0,6,0,56,0,5,60,0,5,6])
print(len(x4))
print(np.count_nonzero(x4))
print(len(x4)-np.count_nonzero(x4))

23
16
7


In [126]:
print(np.mean(x2)) # 평균
print(x2.mean())
print(np.var(x2)) # 분산
print(x2.var())
print(np.std(x2)) # 표준편차
print(x2.std()) 
print(x2.min()) # 최소값
print(x2.max()) # 최대값
print(np.median(x2)) # 중간값 

5.181845913085684
5.181845913085684
5.820082603312546
5.820082603312546
2.4124847363895476
2.4124847363895476
0.319997181410387
10.454062822060958
5.4114971648390515


In [127]:
print(np.percentile(x2,0)) # 최소값
print(np.percentile(x2,25)) # 하위 25%, 제 1사분위수
print(np.percentile(x2,50)) # 중앙값 , 제 2사분위수
print(np.percentile(x2,75)) # 상위 25%, 제 3사분위수
print(np.percentile(x2,100)) # 최대값

0.319997181410387
3.6246164224217696
5.4114971648390515
6.446770053989936
10.454062822060958
